# Generated by Django 5.1.4 on 2024-12-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default='Нет в наличии.')),
                ('image', models.ImageField(upload_to='images/')),
                ('info', models.TextField(default='Описание скоро появится.')),
            ],
        ),
    ]
