# Generated by Django 5.1.4 on 2025-02-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
